### ISSUE TITLE
更新版本，本机密码是多少？可不可以更改下载路径？

### ISSUE THREAD

**Issue by koollylee** [xtulnx/docker-builder#1]

**Comment by xtulnx** [comment]
默认没密码，你可以重载 /app/entrypoint.sh 来主动创建密码；
下载路径你挂载外部目录就行，默认路径为 /root/Downloads/115download;

**Comment by xtulnx** [comment]
已添加环境变量可配置 vnc 密码 **VNC_PASSWORD**
