### ISSUE TITLE
115 要求强制升级，求电脑登录用户密码

### ISSUE THREAD

**Issue by koollylee** [xtulnx/docker-builder#2]
如图，您dockerhub上的[这个项目](https://hub.docker.com/r/xtulnx/novnc-wp115)，原来这一步可以跳过，然后扫码登录，最近重启了一下，现在强制要求升级，现在卡在这个界面，求一下登录密码。
![](http://koollylee.top:8112/images/2022/09/15/20220915211036.png)

**Comment by xtulnx** [comment]
@koollylee 已经更最新 V2.0.0.19（2022-09-02）版本。

还是用：

docker pull xtulnx/novnc-wp115:latest

**Comment by koollylee** [comment]
非常感谢！
