### ISSUE TITLE
版本更新，强制升级，需要输入电脑登录用户密码

### ISSUE THREAD

**Issue by koollylee** [xtulnx/docker-builder#3]
如题，“版本更新，强制升级，需要输入电脑登录用户密码”

大佬，请问这个问题，有一劳永逸的解决方法吗？

![](https://s2.loli.net/2023/03/26/myNOSw9zQZ1vqHV.png)

**Comment by xtulnx** [comment]
@koollylee  已经更新到最新版本 2.0.5.5 （2023-03-27），对应 docker 镜像 tag 用： `xtulnx/novnc-wp115:0.2.6`
